swagger: "2.0"
info:
  version: "1.0.0"
  title: Business Example Service 1
host: localhost:10010
basePath: /
#
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /employee:
    x-swagger-router-controller: employee
    get:
      description: List of employee
      operationId: list
      tags:
        - employee
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Employee"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: Register new employee
      operationId: create
      tags:
        - employee
      responses:
        "201":
          description: Employee registered
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Employee:
    required:
      - firstName
      - lastName
      - ssn
    properties:
      firstName:
        type: string
      lastName:
        type: string
      ssn:
        type: string
      birthday:
        type: string
        format: date
  Error:
    required:
      - message
    properties:
      message:
        type: string
