$schema: http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#
contentVersion: "1.0.0.0"
parameters:
  name:
    type: string
    defaultValue: play-smart-proxy
variables:
  name: "[concat(parameters('name'),'-service1')]"
  server_farm_name: "[variables('name')]"
  server_farm_id: "[resourceId('Microsoft.Web/serverfarms', variables('server_farm_name'))]"
resources:
  -
    name: "[variables('server_farm_name')]"
    type: "Microsoft.Web/serverfarms"
    sku:
      name: S1
      tier: Standard
      capacity: 1
    properties:
      name: "[variables('server_farm_name')]"
      isLinux: false # Really?
    apiVersion: "2015-02-01"
    location: "[resourceGroup().location]"
  -
    name: "[variables('name')]"
    type: "Microsoft.Web/sites"
    properties:
      name: "[variables('name')]"
      serverFarmId: "[variables('server_farm_id')]"
    apiVersion: "2015-08-01"
    location: "[resourceGroup().location]"
    dependsOn:
      - "[variables('server_farm_id')]"
